
POST http://localhost:5000/signup
Content-Type: application/json

{
    "email": "123@gmail.com",
    "name": "123",
    "password": "123123123"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "123@gmail.com",
    "password": "123123123"
}

###

GET  http://localhost:5000/gettoken
Content-Type: application/json
